# JUSTIN NEVER RUN THIS ON YOUR WORK COMP
REGION =  'us-west-2'
ACCESS_KEY_ID = 'AKIAJTR44OGNTNOY3RJA'
SECRET_ACCESS_KEY = 'vLW2mSdYaaItedx1ZlIjsSDTGXMWtXn2B+IjbgUt'
BUCKET = 'background-backups'
PATH = '/Users/justincohen/Documents/'
